package com.example.n_son.roombookingsupport.Model.OjectClass;

/**
 * Created by NSON on 11/19/2017.
 */

public class DatPhong {
    int USER_REGISTER_ID;
    String USER_NAME;
    String DATE_REGISTER;
    int FACILITY_ID;
    String DATE_SUGGEST_ROOM;
    String HOUR_SUGGEST_START;
    String HOUR_SUGGEST_END;
    int FACILITY_COMPONENT_ID_1;
    int FACILITY_COMPONENT_ID_2;
    int FACILITY_COMPONENT_ID_3;
    int FACILITY_COMPONENT_ID_4;
    int FACILITY_COMPONENT_ID_5;
    int FACILITY_COMPONENT_ID_6;
    int FACILITY_COMPONENT_ID_7;
    int FACILITY_COMPONENT_ID_8;
    int FACILITY_COMPONENT_ID_9;
    int FACILITY_COMPONENT_ID_10;
    String CONTENT_REQUEST;


    public DatPhong(int USER_REGISTER_ID, String USER_NAME, String DATE_REGISTER, int FACILITY_ID, String DATE_SUGGEST_ROOM, String HOUR_SUGGEST_START, String HOUR_SUGGEST_END, int FACILITY_COMPONENT_ID_1, int FACILITY_COMPONENT_ID_2, int FACILITY_COMPONENT_ID_3, int FACILITY_COMPONENT_ID_4, int FACILITY_COMPONENT_ID_5, int FACILITY_COMPONENT_ID_6, int FACILITY_COMPONENT_ID_7, int FACILITY_COMPONENT_ID_8, int FACILITY_COMPONENT_ID_9, int FACILITY_COMPONENT_ID_10, String CONTENT_REQUEST) {
        this.USER_REGISTER_ID = USER_REGISTER_ID;
        this.USER_NAME = USER_NAME;
        this.DATE_REGISTER = DATE_REGISTER;
        this.FACILITY_ID = FACILITY_ID;
        this.DATE_SUGGEST_ROOM = DATE_SUGGEST_ROOM;
        this.HOUR_SUGGEST_START = HOUR_SUGGEST_START;
        this.HOUR_SUGGEST_END = HOUR_SUGGEST_END;
        this.FACILITY_COMPONENT_ID_1 = FACILITY_COMPONENT_ID_1;
        this.FACILITY_COMPONENT_ID_2 = FACILITY_COMPONENT_ID_2;
        this.FACILITY_COMPONENT_ID_3 = FACILITY_COMPONENT_ID_3;
        this.FACILITY_COMPONENT_ID_4 = FACILITY_COMPONENT_ID_4;
        this.FACILITY_COMPONENT_ID_5 = FACILITY_COMPONENT_ID_5;
        this.FACILITY_COMPONENT_ID_6 = FACILITY_COMPONENT_ID_6;
        this.FACILITY_COMPONENT_ID_7 = FACILITY_COMPONENT_ID_7;
        this.FACILITY_COMPONENT_ID_8 = FACILITY_COMPONENT_ID_8;
        this.FACILITY_COMPONENT_ID_9 = FACILITY_COMPONENT_ID_9;
        this.FACILITY_COMPONENT_ID_10 = FACILITY_COMPONENT_ID_10;
        this.CONTENT_REQUEST = CONTENT_REQUEST;
    }

    public int getUSER_REGISTER_ID() {
        return USER_REGISTER_ID;
    }

    public void setUSER_REGISTER_ID(int USER_REGISTER_ID) {
        this.USER_REGISTER_ID = USER_REGISTER_ID;
    }

    public String getUSER_NAME() {
        return USER_NAME;
    }

    public void setUSER_NAME(String USER_NAME) {
        this.USER_NAME = USER_NAME;
    }

    public String getDATE_REGISTER() {
        return DATE_REGISTER;
    }

    public void setDATE_REGISTER(String DATE_REGISTER) {
        this.DATE_REGISTER = DATE_REGISTER;
    }

    public int getFACILITY_ID() {
        return FACILITY_ID;
    }

    public void setFACILITY_ID(int FACILITY_ID) {
        this.FACILITY_ID = FACILITY_ID;
    }

    public String getDATE_SUGGEST_ROOM() {
        return DATE_SUGGEST_ROOM;
    }

    public void setDATE_SUGGEST_ROOM(String DATE_SUGGEST_ROOM) {
        this.DATE_SUGGEST_ROOM = DATE_SUGGEST_ROOM;
    }

    public String getHOUR_SUGGEST_START() {
        return HOUR_SUGGEST_START;
    }

    public void setHOUR_SUGGEST_START(String HOUR_SUGGEST_START) {
        this.HOUR_SUGGEST_START = HOUR_SUGGEST_START;
    }

    public String getHOUR_SUGGEST_END() {
        return HOUR_SUGGEST_END;
    }

    public void setHOUR_SUGGEST_END(String HOUR_SUGGEST_END) {
        this.HOUR_SUGGEST_END = HOUR_SUGGEST_END;
    }

    public int getFACILITY_COMPONENT_ID_1() {
        return FACILITY_COMPONENT_ID_1;
    }

    public void setFACILITY_COMPONENT_ID_1(int FACILITY_COMPONENT_ID_1) {
        this.FACILITY_COMPONENT_ID_1 = FACILITY_COMPONENT_ID_1;
    }

    public int getFACILITY_COMPONENT_ID_2() {
        return FACILITY_COMPONENT_ID_2;
    }

    public void setFACILITY_COMPONENT_ID_2(int FACILITY_COMPONENT_ID_2) {
        this.FACILITY_COMPONENT_ID_2 = FACILITY_COMPONENT_ID_2;
    }

    public int getFACILITY_COMPONENT_ID_3() {
        return FACILITY_COMPONENT_ID_3;
    }

    public void setFACILITY_COMPONENT_ID_3(int FACILITY_COMPONENT_ID_3) {
        this.FACILITY_COMPONENT_ID_3 = FACILITY_COMPONENT_ID_3;
    }

    public int getFACILITY_COMPONENT_ID_4() {
        return FACILITY_COMPONENT_ID_4;
    }

    public void setFACILITY_COMPONENT_ID_4(int FACILITY_COMPONENT_ID_4) {
        this.FACILITY_COMPONENT_ID_4 = FACILITY_COMPONENT_ID_4;
    }

    public int getFACILITY_COMPONENT_ID_5() {
        return FACILITY_COMPONENT_ID_5;
    }

    public void setFACILITY_COMPONENT_ID_5(int FACILITY_COMPONENT_ID_5) {
        this.FACILITY_COMPONENT_ID_5 = FACILITY_COMPONENT_ID_5;
    }

    public int getFACILITY_COMPONENT_ID_6() {
        return FACILITY_COMPONENT_ID_6;
    }

    public void setFACILITY_COMPONENT_ID_6(int FACILITY_COMPONENT_ID_6) {
        this.FACILITY_COMPONENT_ID_6 = FACILITY_COMPONENT_ID_6;
    }

    public int getFACILITY_COMPONENT_ID_7() {
        return FACILITY_COMPONENT_ID_7;
    }

    public void setFACILITY_COMPONENT_ID_7(int FACILITY_COMPONENT_ID_7) {
        this.FACILITY_COMPONENT_ID_7 = FACILITY_COMPONENT_ID_7;
    }

    public int getFACILITY_COMPONENT_ID_8() {
        return FACILITY_COMPONENT_ID_8;
    }

    public void setFACILITY_COMPONENT_ID_8(int FACILITY_COMPONENT_ID_8) {
        this.FACILITY_COMPONENT_ID_8 = FACILITY_COMPONENT_ID_8;
    }

    public int getFACILITY_COMPONENT_ID_9() {
        return FACILITY_COMPONENT_ID_9;
    }

    public void setFACILITY_COMPONENT_ID_9(int FACILITY_COMPONENT_ID_9) {
        this.FACILITY_COMPONENT_ID_9 = FACILITY_COMPONENT_ID_9;
    }

    public int getFACILITY_COMPONENT_ID_10() {
        return FACILITY_COMPONENT_ID_10;
    }

    public void setFACILITY_COMPONENT_ID_10(int FACILITY_COMPONENT_ID_10) {
        this.FACILITY_COMPONENT_ID_10 = FACILITY_COMPONENT_ID_10;
    }

    public String getCONTENT_REQUEST() {
        return CONTENT_REQUEST;
    }

    public void setCONTENT_REQUEST(String CONTENT_REQUEST) {
        this.CONTENT_REQUEST = CONTENT_REQUEST;
    }
}
